version: '2'

services:

  db:
    image: postgres:9.6.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cryptonewsDB

  scraper:
    build: .
    entrypoint: /bin/bash ./entrypoint.sh run_scraper
    environment:
      - DJANGO_SETTINGS_MODULE=crypto_news.docker_settings
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - IOTA_SLACK_WEBHOOK_URL=${IOTA_SLACK_WEBHOOK_URL}
      - MODUM_SLACK_WEBHOOK_URL=${MODUM_SLACK_WEBHOOK_URL}
      - ETC_SLACK_WEBHOOK_URL=${ETC_SLACK_WEBHOOK_URL}
      - LTC_SLACK_WEBHOOK_URL=${LTC_SLACK_WEBHOOK_URL}
      - BCH_SLACK_WEBHOOK_URL=${BCH_SLACK_WEBHOOK_URL}
    restart: on-failure
    links:
      - db:cryptonews-db