# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_url', models.TextField()),
                ('crawler_id', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('text', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'verbose_name': 'News Article',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField()),
                ('creator', models.TextField(default='')),
                ('identifier', models.TextField(unique=True)),
                ('linked_token', models.CharField(max_length=10)),
                ('text', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Twitter Tweets',
                'verbose_name': 'Twitter Tweet',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together=set([('identifier', 'linked_token')]),
        ),
        migrations.AlterUniqueTogether(
            name='newsarticle',
            unique_together=set([('crawler_id', 'title', 'url')]),
        ),
    ]
