# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcomment',
            name='body',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='body_html',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='redditsubmission',
            name='self_text',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='redditsubmission',
            name='self_text_html',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
