# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('validated', models.BooleanField(default=False)),
                ('source_id', models.PositiveIntegerField()),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
    ]
