# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0003_auto_20170913_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedevent',
            name='relevant_coins',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('iota', 'Iota'), ('etc', 'Ethereum Classic'), ('eth', 'Ethereum'), ('btc', 'Bitcoin'), ('dash', 'Dash'), ('bth', 'Bitcoin Cash'), ('xrp', 'Ripple'), ('nem', 'NEM'), ('xmr', 'Monero'), ('omg', 'OmiseGO'), ('neo', 'NEO'), ('ltc', 'Litecoin')], default=('none', 'None'), max_length=54),
        ),
    ]
