# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0004_detectedevent_relevant_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedevent',
            name='is_validat',
            field=models.BooleanField(default=True),
        ),
    ]
