# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0005_detectedevent_is_validat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedevent',
            old_name='is_validat',
            new_name='is_valid',
        ),
    ]
